spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_USERNAME}
spring.datasource.password=${SPRING_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sigmausco@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=8000
spring.mail.properties.mail.smtp.writetimeout=8000
spring.mail.default-encoding=UTF-8
file.upload-dir=./SIGMA-uploads/SIGMA-files
frontend.url=https://modalidad.grado.fac-ingenieria-usco.com
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
